// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// structures

char * BinaryTree_gc_map = "";

struct BinaryTree
{
  struct BinaryTree_vtable *vptr;
};

char * BT_gc_map = "";

struct BT
{
  struct BT_vtable *vptr;
};

char * Tree_gc_map = "110001";

struct Tree
{
  struct Tree_vtable *vptr;
  struct Tree * left;
  struct Tree * right;
  int key;
  int has_left;
  int has_right;
  struct Tree * my_null;
};
// vtables structures
struct BinaryTree_vtable
{
  char *BinaryTree_gc_map;
};

struct BT_vtable
{
  char *BT_gc_map;
  int (*Start)();
};

struct Tree_vtable
{
  char *Tree_gc_map;
  int (*Init)();
  int (*SetRight)();
  int (*SetLeft)();
  struct Tree * (*GetRight)();
  struct Tree * (*GetLeft)();
  int (*GetKey)();
  int (*SetKey)();
  int (*GetHas_Right)();
  int (*GetHas_Left)();
  int (*SetHas_Left)();
  int (*SetHas_Right)();
  int (*Compare)();
  int (*Insert)();
  int (*Delete)();
  int (*Remove)();
  int (*RemoveRight)();
  int (*RemoveLeft)();
  int (*Search)();
  int (*Print)();
  int (*RecPrint)();
};


// methods dec
int BT_Start(struct BT * this);
int Tree_Init(struct Tree * this, int v_key);
int Tree_SetRight(struct Tree * this, struct Tree * rn);
int Tree_SetLeft(struct Tree * this, struct Tree * ln);
struct Tree * Tree_GetRight(struct Tree * this);
struct Tree * Tree_GetLeft(struct Tree * this);
int Tree_GetKey(struct Tree * this);
int Tree_SetKey(struct Tree * this, int v_key);
int Tree_GetHas_Right(struct Tree * this);
int Tree_GetHas_Left(struct Tree * this);
int Tree_SetHas_Left(struct Tree * this, int val);
int Tree_SetHas_Right(struct Tree * this, int val);
int Tree_Compare(struct Tree * this, int num1, int num2);
int Tree_Insert(struct Tree * this, int v_key);
int Tree_Delete(struct Tree * this, int v_key);
int Tree_Remove(struct Tree * this, struct Tree * p_node, struct Tree * c_node);
int Tree_RemoveRight(struct Tree * this, struct Tree * p_node, struct Tree * c_node);
int Tree_RemoveLeft(struct Tree * this, struct Tree * p_node, struct Tree * c_node);
int Tree_Search(struct Tree * this, int v_key);
int Tree_Print(struct Tree * this);
int Tree_RecPrint(struct Tree * this, struct Tree * node);


extern void * prev;
// vtables
struct BinaryTree_vtable BinaryTree_vtable_ = 
{
  &BinaryTree_gc_map,
};

struct BT_vtable BT_vtable_ = 
{
  &BT_gc_map,
  BT_Start,
};

struct Tree_vtable Tree_vtable_ = 
{
  &Tree_gc_map,
  Tree_Init,
  Tree_SetRight,
  Tree_SetLeft,
  Tree_GetRight,
  Tree_GetLeft,
  Tree_GetKey,
  Tree_SetKey,
  Tree_GetHas_Right,
  Tree_GetHas_Left,
  Tree_SetHas_Left,
  Tree_SetHas_Right,
  Tree_Compare,
  Tree_Insert,
  Tree_Delete,
  Tree_Remove,
  Tree_RemoveRight,
  Tree_RemoveLeft,
  Tree_Search,
  Tree_Print,
  Tree_RecPrint,
};


// methods
char * BT_Start_arguments_gc_map = "1";
char * BT_Start_locals_gc_map = "1001111111111111111111";
struct BT_Start_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
  struct Tree *	root;
  struct Tree *	x_1;
  struct Tree *	x_2;
  struct Tree *	x_3;
  struct Tree *	x_4;
  struct Tree *	x_5;
  struct Tree *	x_6;
  struct Tree *	x_7;
  struct Tree *	x_8;
  struct Tree *	x_9;
  struct Tree *	x_10;
  struct Tree *	x_11;
  struct Tree *	x_12;
  struct Tree *	x_13;
  struct Tree *	x_14;
  struct Tree *	x_15;
  struct Tree *	x_16;
  struct Tree *	x_17;
  struct Tree *	x_18;
  struct Tree *	x_19;
};

int BT_Start(struct BT * this)
{
  struct BT_Start_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = BT_Start_arguments_gc_map;
  frame.arguments_base_address = &this;
  frame.locals_gc_map = BT_Start_locals_gc_map;


  frame.root = 0;
  int ntb;
  int nti;
  frame.x_1 = 0;
  frame.x_2 = 0;
  frame.x_3 = 0;
  frame.x_4 = 0;
  frame.x_5 = 0;
  frame.x_6 = 0;
  frame.x_7 = 0;
  frame.x_8 = 0;
  frame.x_9 = 0;
  frame.x_10 = 0;
  frame.x_11 = 0;
  frame.x_12 = 0;
  frame.x_13 = 0;
  frame.x_14 = 0;
  frame.x_15 = 0;
  frame.x_16 = 0;
  frame.x_17 = 0;
  frame.x_18 = 0;
  frame.x_19 = 0;

  frame.root = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
  ntb = (frame.x_1=frame.root, frame.x_1->vptr->Init(frame.x_1, 16));
  ntb = (frame.x_2=frame.root, frame.x_2->vptr->Print(frame.x_2));
  System_out_println (100000000);
  ntb = (frame.x_3=frame.root, frame.x_3->vptr->Insert(frame.x_3, 8));
  ntb = (frame.x_4=frame.root, frame.x_4->vptr->Print(frame.x_4));
  ntb = (frame.x_5=frame.root, frame.x_5->vptr->Insert(frame.x_5, 24));
  ntb = (frame.x_6=frame.root, frame.x_6->vptr->Insert(frame.x_6, 4));
  ntb = (frame.x_7=frame.root, frame.x_7->vptr->Insert(frame.x_7, 12));
  ntb = (frame.x_8=frame.root, frame.x_8->vptr->Insert(frame.x_8, 20));
  ntb = (frame.x_9=frame.root, frame.x_9->vptr->Insert(frame.x_9, 28));
  ntb = (frame.x_10=frame.root, frame.x_10->vptr->Insert(frame.x_10, 14));
  ntb = (frame.x_11=frame.root, frame.x_11->vptr->Print(frame.x_11));
  System_out_println ((frame.x_12=frame.root, frame.x_12->vptr->Search(frame.x_12, 24)));
  System_out_println ((frame.x_13=frame.root, frame.x_13->vptr->Search(frame.x_13, 12)));
  System_out_println ((frame.x_14=frame.root, frame.x_14->vptr->Search(frame.x_14, 16)));
  System_out_println ((frame.x_15=frame.root, frame.x_15->vptr->Search(frame.x_15, 50)));
  System_out_println ((frame.x_16=frame.root, frame.x_16->vptr->Search(frame.x_16, 12)));
  ntb = (frame.x_17=frame.root, frame.x_17->vptr->Delete(frame.x_17, 12));
  ntb = (frame.x_18=frame.root, frame.x_18->vptr->Print(frame.x_18));
  System_out_println ((frame.x_19=frame.root, frame.x_19->vptr->Search(frame.x_19, 12)));
  prev  = frame.prev;
  return 0;
}
char * Tree_Init_arguments_gc_map = "10";
char * Tree_Init_locals_gc_map = "";
struct Tree_Init_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
};

int Tree_Init(struct Tree * this, int v_key)
{
  struct Tree_Init_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Tree_Init_arguments_gc_map;
  frame.arguments_base_address = &this;
  frame.locals_gc_map = Tree_Init_locals_gc_map;



  this->key = v_key;
  this->has_left = 0;
  this->has_right = 0;
  prev  = frame.prev;
  return 1;
}
char * Tree_SetRight_arguments_gc_map = "11";
char * Tree_SetRight_locals_gc_map = "";
struct Tree_SetRight_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
};

int Tree_SetRight(struct Tree * this, struct Tree * rn)
{
  struct Tree_SetRight_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Tree_SetRight_arguments_gc_map;
  frame.arguments_base_address = &this;
  frame.locals_gc_map = Tree_SetRight_locals_gc_map;



  this->right = rn;
  prev  = frame.prev;
  return 1;
}
char * Tree_SetLeft_arguments_gc_map = "11";
char * Tree_SetLeft_locals_gc_map = "";
struct Tree_SetLeft_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
};

int Tree_SetLeft(struct Tree * this, struct Tree * ln)
{
  struct Tree_SetLeft_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Tree_SetLeft_arguments_gc_map;
  frame.arguments_base_address = &this;
  frame.locals_gc_map = Tree_SetLeft_locals_gc_map;



  this->left = ln;
  prev  = frame.prev;
  return 1;
}
char * Tree_GetRight_arguments_gc_map = "1";
char * Tree_GetRight_locals_gc_map = "";
struct Tree_GetRight_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
};

struct Tree * Tree_GetRight(struct Tree * this)
{
  struct Tree_GetRight_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Tree_GetRight_arguments_gc_map;
  frame.arguments_base_address = &this;
  frame.locals_gc_map = Tree_GetRight_locals_gc_map;



  prev  = frame.prev;
  return this->right;
}
char * Tree_GetLeft_arguments_gc_map = "1";
char * Tree_GetLeft_locals_gc_map = "";
struct Tree_GetLeft_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
};

struct Tree * Tree_GetLeft(struct Tree * this)
{
  struct Tree_GetLeft_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Tree_GetLeft_arguments_gc_map;
  frame.arguments_base_address = &this;
  frame.locals_gc_map = Tree_GetLeft_locals_gc_map;



  prev  = frame.prev;
  return this->left;
}
char * Tree_GetKey_arguments_gc_map = "1";
char * Tree_GetKey_locals_gc_map = "";
struct Tree_GetKey_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
};

int Tree_GetKey(struct Tree * this)
{
  struct Tree_GetKey_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Tree_GetKey_arguments_gc_map;
  frame.arguments_base_address = &this;
  frame.locals_gc_map = Tree_GetKey_locals_gc_map;



  prev  = frame.prev;
  return this->key;
}
char * Tree_SetKey_arguments_gc_map = "10";
char * Tree_SetKey_locals_gc_map = "";
struct Tree_SetKey_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
};

int Tree_SetKey(struct Tree * this, int v_key)
{
  struct Tree_SetKey_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Tree_SetKey_arguments_gc_map;
  frame.arguments_base_address = &this;
  frame.locals_gc_map = Tree_SetKey_locals_gc_map;



  this->key = v_key;
  prev  = frame.prev;
  return 1;
}
char * Tree_GetHas_Right_arguments_gc_map = "1";
char * Tree_GetHas_Right_locals_gc_map = "";
struct Tree_GetHas_Right_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
};

int Tree_GetHas_Right(struct Tree * this)
{
  struct Tree_GetHas_Right_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Tree_GetHas_Right_arguments_gc_map;
  frame.arguments_base_address = &this;
  frame.locals_gc_map = Tree_GetHas_Right_locals_gc_map;



  prev  = frame.prev;
  return this->has_right;
}
char * Tree_GetHas_Left_arguments_gc_map = "1";
char * Tree_GetHas_Left_locals_gc_map = "";
struct Tree_GetHas_Left_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
};

int Tree_GetHas_Left(struct Tree * this)
{
  struct Tree_GetHas_Left_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Tree_GetHas_Left_arguments_gc_map;
  frame.arguments_base_address = &this;
  frame.locals_gc_map = Tree_GetHas_Left_locals_gc_map;



  prev  = frame.prev;
  return this->has_left;
}
char * Tree_SetHas_Left_arguments_gc_map = "10";
char * Tree_SetHas_Left_locals_gc_map = "";
struct Tree_SetHas_Left_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
};

int Tree_SetHas_Left(struct Tree * this, int val)
{
  struct Tree_SetHas_Left_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Tree_SetHas_Left_arguments_gc_map;
  frame.arguments_base_address = &this;
  frame.locals_gc_map = Tree_SetHas_Left_locals_gc_map;



  this->has_left = val;
  prev  = frame.prev;
  return 1;
}
char * Tree_SetHas_Right_arguments_gc_map = "10";
char * Tree_SetHas_Right_locals_gc_map = "";
struct Tree_SetHas_Right_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
};

int Tree_SetHas_Right(struct Tree * this, int val)
{
  struct Tree_SetHas_Right_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Tree_SetHas_Right_arguments_gc_map;
  frame.arguments_base_address = &this;
  frame.locals_gc_map = Tree_SetHas_Right_locals_gc_map;



  this->has_right = val;
  prev  = frame.prev;
  return 1;
}
char * Tree_Compare_arguments_gc_map = "100";
char * Tree_Compare_locals_gc_map = "00";
struct Tree_Compare_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
};

int Tree_Compare(struct Tree * this, int num1, int num2)
{
  struct Tree_Compare_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Tree_Compare_arguments_gc_map;
  frame.arguments_base_address = &this;
  frame.locals_gc_map = Tree_Compare_locals_gc_map;


  int ntb;
  int nti;

  ntb = 0;
  nti = num2 + 1;
  if (num1 < num2)
    ntb = 0;

  else
    if (!(num1 < nti))
      ntb = 0;

    else
      ntb = 1;


  prev  = frame.prev;
  return ntb;
}
char * Tree_Insert_arguments_gc_map = "10";
char * Tree_Insert_locals_gc_map = "100011111111111";
struct Tree_Insert_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
  struct Tree *	new_node;
  struct Tree *	current_node;
  struct Tree *	x_20;
  struct Tree *	x_21;
  struct Tree *	x_22;
  struct Tree *	x_23;
  struct Tree *	x_24;
  struct Tree *	x_25;
  struct Tree *	x_26;
  struct Tree *	x_27;
  struct Tree *	x_28;
  struct Tree *	x_29;
};

int Tree_Insert(struct Tree * this, int v_key)
{
  struct Tree_Insert_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Tree_Insert_arguments_gc_map;
  frame.arguments_base_address = &this;
  frame.locals_gc_map = Tree_Insert_locals_gc_map;


  frame.new_node = 0;
  int ntb;
  int cont;
  int key_aux;
  frame.current_node = 0;
  frame.x_20 = 0;
  frame.x_21 = 0;
  frame.x_22 = 0;
  frame.x_23 = 0;
  frame.x_24 = 0;
  frame.x_25 = 0;
  frame.x_26 = 0;
  frame.x_27 = 0;
  frame.x_28 = 0;
  frame.x_29 = 0;

  frame.new_node = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
  ntb = (frame.x_20=frame.new_node, frame.x_20->vptr->Init(frame.x_20, v_key));
  frame.current_node = this;
  cont = 1;
  while (cont)
  {
    key_aux = (frame.x_21=frame.current_node, frame.x_21->vptr->GetKey(frame.x_21));
    if (v_key < key_aux)
    {
      if ((frame.x_22=frame.current_node, frame.x_22->vptr->GetHas_Left(frame.x_22)))
        frame.current_node = (frame.x_23=frame.current_node, frame.x_23->vptr->GetLeft(frame.x_23));

      else
      {
        cont = 0;
        ntb = (frame.x_24=frame.current_node, frame.x_24->vptr->SetHas_Left(frame.x_24, 1));
        ntb = (frame.x_25=frame.current_node, frame.x_25->vptr->SetLeft(frame.x_25, frame.new_node));
        }

      }

    else
    {
      if ((frame.x_26=frame.current_node, frame.x_26->vptr->GetHas_Right(frame.x_26)))
        frame.current_node = (frame.x_27=frame.current_node, frame.x_27->vptr->GetRight(frame.x_27));

      else
      {
        cont = 0;
        ntb = (frame.x_28=frame.current_node, frame.x_28->vptr->SetHas_Right(frame.x_28, 1));
        ntb = (frame.x_29=frame.current_node, frame.x_29->vptr->SetRight(frame.x_29, frame.new_node));
        }

      }

    }

  prev  = frame.prev;
  return 1;
}
char * Tree_Delete_arguments_gc_map = "10";
char * Tree_Delete_locals_gc_map = "1100000111111111";
struct Tree_Delete_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
  struct Tree *	current_node;
  struct Tree *	parent_node;
  struct Tree *	x_30;
  struct Tree *	x_31;
  struct Tree *	x_32;
  struct Tree *	x_33;
  struct Tree *	x_34;
  struct Tree *	x_35;
  struct Tree *	x_36;
  struct Tree *	x_37;
  struct Tree *	x_38;
};

int Tree_Delete(struct Tree * this, int v_key)
{
  struct Tree_Delete_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Tree_Delete_arguments_gc_map;
  frame.arguments_base_address = &this;
  frame.locals_gc_map = Tree_Delete_locals_gc_map;


  frame.current_node = 0;
  frame.parent_node = 0;
  int cont;
  int found;
  int is_root;
  int key_aux;
  int ntb;
  frame.x_30 = 0;
  frame.x_31 = 0;
  frame.x_32 = 0;
  frame.x_33 = 0;
  frame.x_34 = 0;
  frame.x_35 = 0;
  frame.x_36 = 0;
  frame.x_37 = 0;
  frame.x_38 = 0;

    frame.current_node = this;
    frame.parent_node = this;
    cont = 1;
    found = 0;
    is_root = 1;
    while (cont)
    {
      key_aux = (frame.x_30=frame.current_node, frame.x_30->vptr->GetKey(frame.x_30));
      if (v_key < key_aux)
        if ((frame.x_31=frame.current_node, frame.x_31->vptr->GetHas_Left(frame.x_31)))
        {
          frame.parent_node = frame.current_node;
          frame.current_node = (frame.x_32=frame.current_node, frame.x_32->vptr->GetLeft(frame.x_32));
          }

        else
          cont = 0;


      else
        if (key_aux < v_key)
          if ((frame.x_33=frame.current_node, frame.x_33->vptr->GetHas_Right(frame.x_33)))
          {
            frame.parent_node = frame.current_node;
            frame.current_node = (frame.x_34=frame.current_node, frame.x_34->vptr->GetRight(frame.x_34));
            }

          else
            cont = 0;


        else
        {
          if (is_root)
            if (!((frame.x_35=frame.current_node, frame.x_35->vptr->GetHas_Right(frame.x_35))) && !((frame.x_36=frame.current_node, frame.x_36->vptr->GetHas_Left(frame.x_36))))
              ntb = 1;

            else
              ntb = (frame.x_37=this, frame.x_37->vptr->Remove(frame.x_37, frame.parent_node, frame.current_node));


          else
            ntb = (frame.x_38=this, frame.x_38->vptr->Remove(frame.x_38, frame.parent_node, frame.current_node));

          found = 1;
          cont = 0;
          }


      is_root = 0;
      }

  prev  = frame.prev;
  return found;
}
char * Tree_Remove_arguments_gc_map = "111";
char * Tree_Remove_locals_gc_map = "000111111111111";
struct Tree_Remove_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
  struct Tree *	x_39;
  struct Tree *	x_40;
  struct Tree *	x_41;
  struct Tree *	x_42;
  struct Tree *	x_43;
  struct Tree *	x_44;
  struct Tree *	x_45;
  struct Tree *	x_46;
  struct Tree *	x_47;
  struct Tree *	x_48;
  struct Tree *	x_49;
  struct Tree *	x_50;
};

int Tree_Remove(struct Tree * this, struct Tree * p_node, struct Tree * c_node)
{
  struct Tree_Remove_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Tree_Remove_arguments_gc_map;
  frame.arguments_base_address = &this;
  frame.locals_gc_map = Tree_Remove_locals_gc_map;


  int ntb;
  int auxkey1;
  int auxkey2;
  frame.x_39 = 0;
  frame.x_40 = 0;
  frame.x_41 = 0;
  frame.x_42 = 0;
  frame.x_43 = 0;
  frame.x_44 = 0;
  frame.x_45 = 0;
  frame.x_46 = 0;
  frame.x_47 = 0;
  frame.x_48 = 0;
  frame.x_49 = 0;
  frame.x_50 = 0;

      if ((frame.x_39=c_node, frame.x_39->vptr->GetHas_Left(frame.x_39)))
        ntb = (frame.x_40=this, frame.x_40->vptr->RemoveLeft(frame.x_40, p_node, c_node));

      else
        if ((frame.x_41=c_node, frame.x_41->vptr->GetHas_Right(frame.x_41)))
          ntb = (frame.x_42=this, frame.x_42->vptr->RemoveRight(frame.x_42, p_node, c_node));

        else
        {
          auxkey1 = (frame.x_43=c_node, frame.x_43->vptr->GetKey(frame.x_43));
          auxkey2 = (frame.x_45=(frame.x_44=p_node, frame.x_44->vptr->GetLeft(frame.x_44)), frame.x_45->vptr->GetKey(frame.x_45));
          if ((frame.x_46=this, frame.x_46->vptr->Compare(frame.x_46, auxkey1, auxkey2)))
          {
            ntb = (frame.x_47=p_node, frame.x_47->vptr->SetLeft(frame.x_47, this->my_null));
            ntb = (frame.x_48=p_node, frame.x_48->vptr->SetHas_Left(frame.x_48, 0));
            }

          else
          {
            ntb = (frame.x_49=p_node, frame.x_49->vptr->SetRight(frame.x_49, this->my_null));
            ntb = (frame.x_50=p_node, frame.x_50->vptr->SetHas_Right(frame.x_50, 0));
            }

          }


  prev  = frame.prev;
  return 1;
}
char * Tree_RemoveRight_arguments_gc_map = "111";
char * Tree_RemoveRight_locals_gc_map = "01111111";
struct Tree_RemoveRight_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
  struct Tree *	x_51;
  struct Tree *	x_52;
  struct Tree *	x_53;
  struct Tree *	x_54;
  struct Tree *	x_55;
  struct Tree *	x_56;
  struct Tree *	x_57;
};

int Tree_RemoveRight(struct Tree * this, struct Tree * p_node, struct Tree * c_node)
{
  struct Tree_RemoveRight_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Tree_RemoveRight_arguments_gc_map;
  frame.arguments_base_address = &this;
  frame.locals_gc_map = Tree_RemoveRight_locals_gc_map;


  int ntb;
  frame.x_51 = 0;
  frame.x_52 = 0;
  frame.x_53 = 0;
  frame.x_54 = 0;
  frame.x_55 = 0;
  frame.x_56 = 0;
  frame.x_57 = 0;

      while ((frame.x_51=c_node, frame.x_51->vptr->GetHas_Right(frame.x_51)))
      {
        ntb = (frame.x_52=c_node, frame.x_52->vptr->SetKey(frame.x_52, (frame.x_54=(frame.x_53=c_node, frame.x_53->vptr->GetRight(frame.x_53)), frame.x_54->vptr->GetKey(frame.x_54))));
        p_node = c_node;
        c_node = (frame.x_55=c_node, frame.x_55->vptr->GetRight(frame.x_55));
        }

        ntb = (frame.x_56=p_node, frame.x_56->vptr->SetRight(frame.x_56, this->my_null));
        ntb = (frame.x_57=p_node, frame.x_57->vptr->SetHas_Right(frame.x_57, 0));
  prev  = frame.prev;
  return 1;
}
char * Tree_RemoveLeft_arguments_gc_map = "111";
char * Tree_RemoveLeft_locals_gc_map = "01111111";
struct Tree_RemoveLeft_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
  struct Tree *	x_58;
  struct Tree *	x_59;
  struct Tree *	x_60;
  struct Tree *	x_61;
  struct Tree *	x_62;
  struct Tree *	x_63;
  struct Tree *	x_64;
};

int Tree_RemoveLeft(struct Tree * this, struct Tree * p_node, struct Tree * c_node)
{
  struct Tree_RemoveLeft_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Tree_RemoveLeft_arguments_gc_map;
  frame.arguments_base_address = &this;
  frame.locals_gc_map = Tree_RemoveLeft_locals_gc_map;


  int ntb;
  frame.x_58 = 0;
  frame.x_59 = 0;
  frame.x_60 = 0;
  frame.x_61 = 0;
  frame.x_62 = 0;
  frame.x_63 = 0;
  frame.x_64 = 0;

        while ((frame.x_58=c_node, frame.x_58->vptr->GetHas_Left(frame.x_58)))
        {
          ntb = (frame.x_59=c_node, frame.x_59->vptr->SetKey(frame.x_59, (frame.x_61=(frame.x_60=c_node, frame.x_60->vptr->GetLeft(frame.x_60)), frame.x_61->vptr->GetKey(frame.x_61))));
          p_node = c_node;
          c_node = (frame.x_62=c_node, frame.x_62->vptr->GetLeft(frame.x_62));
          }

          ntb = (frame.x_63=p_node, frame.x_63->vptr->SetLeft(frame.x_63, this->my_null));
          ntb = (frame.x_64=p_node, frame.x_64->vptr->SetHas_Left(frame.x_64, 0));
  prev  = frame.prev;
  return 1;
}
char * Tree_Search_arguments_gc_map = "10";
char * Tree_Search_locals_gc_map = "001011111";
struct Tree_Search_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
  struct Tree *	current_node;
  struct Tree *	x_65;
  struct Tree *	x_66;
  struct Tree *	x_67;
  struct Tree *	x_68;
  struct Tree *	x_69;
};

int Tree_Search(struct Tree * this, int v_key)
{
  struct Tree_Search_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Tree_Search_arguments_gc_map;
  frame.arguments_base_address = &this;
  frame.locals_gc_map = Tree_Search_locals_gc_map;


  int cont;
  int ifound;
  frame.current_node = 0;
  int key_aux;
  frame.x_65 = 0;
  frame.x_66 = 0;
  frame.x_67 = 0;
  frame.x_68 = 0;
  frame.x_69 = 0;

          frame.current_node = this;
          cont = 1;
          ifound = 0;
          while (cont)
          {
            key_aux = (frame.x_65=frame.current_node, frame.x_65->vptr->GetKey(frame.x_65));
            if (v_key < key_aux)
              if ((frame.x_66=frame.current_node, frame.x_66->vptr->GetHas_Left(frame.x_66)))
                frame.current_node = (frame.x_67=frame.current_node, frame.x_67->vptr->GetLeft(frame.x_67));

              else
                cont = 0;


            else
              if (key_aux < v_key)
                if ((frame.x_68=frame.current_node, frame.x_68->vptr->GetHas_Right(frame.x_68)))
                  frame.current_node = (frame.x_69=frame.current_node, frame.x_69->vptr->GetRight(frame.x_69));

                else
                  cont = 0;


              else
              {
                ifound = 1;
                cont = 0;
                }


            }

  prev  = frame.prev;
  return ifound;
}
char * Tree_Print_arguments_gc_map = "1";
char * Tree_Print_locals_gc_map = "101";
struct Tree_Print_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
  struct Tree *	current_node;
  struct Tree *	x_70;
};

int Tree_Print(struct Tree * this)
{
  struct Tree_Print_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Tree_Print_arguments_gc_map;
  frame.arguments_base_address = &this;
  frame.locals_gc_map = Tree_Print_locals_gc_map;


  frame.current_node = 0;
  int ntb;
  frame.x_70 = 0;

            frame.current_node = this;
            ntb = (frame.x_70=this, frame.x_70->vptr->RecPrint(frame.x_70, frame.current_node));
  prev  = frame.prev;
  return 1;
}
char * Tree_RecPrint_arguments_gc_map = "11";
char * Tree_RecPrint_locals_gc_map = "01111111";
struct Tree_RecPrint_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
  struct Tree *	x_71;
  struct Tree *	x_72;
  struct Tree *	x_73;
  struct Tree *	x_74;
  struct Tree *	x_75;
  struct Tree *	x_76;
  struct Tree *	x_77;
};

int Tree_RecPrint(struct Tree * this, struct Tree * node)
{
  struct Tree_RecPrint_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Tree_RecPrint_arguments_gc_map;
  frame.arguments_base_address = &this;
  frame.locals_gc_map = Tree_RecPrint_locals_gc_map;


  int ntb;
  frame.x_71 = 0;
  frame.x_72 = 0;
  frame.x_73 = 0;
  frame.x_74 = 0;
  frame.x_75 = 0;
  frame.x_76 = 0;
  frame.x_77 = 0;

            if ((frame.x_71=node, frame.x_71->vptr->GetHas_Left(frame.x_71)))
            {
              ntb = (frame.x_72=this, frame.x_72->vptr->RecPrint(frame.x_72, (frame.x_73=node, frame.x_73->vptr->GetLeft(frame.x_73))));
              }

            else
              ntb = 1;

  System_out_println ((frame.x_74=node, frame.x_74->vptr->GetKey(frame.x_74)));
            if ((frame.x_75=node, frame.x_75->vptr->GetHas_Right(frame.x_75)))
            {
              ntb = (frame.x_76=this, frame.x_76->vptr->RecPrint(frame.x_76, (frame.x_77=node, frame.x_77->vptr->GetRight(frame.x_77))));
              }

            else
              ntb = 1;

  prev  = frame.prev;
  return 1;
}

// main method
char * Tiger_main_locals_gc_map = "1";
struct Tiger_main_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
  struct BT *	x_0;
};

int Tiger_main ()
{
  struct Tiger_main_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "";
  frame.arguments_base_address = "";
  frame.locals_gc_map = Tiger_main_locals_gc_map;


  frame.x_0 = 0;

  System_out_println ((frame.x_0=((struct BT*)(Tiger_new (&BT_vtable_, sizeof(struct BT)))), frame.x_0->vptr->Start(frame.x_0)));
}




