// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// structures

char * DeadClass_gc_map = "";

struct DeadClass
{
  struct DeadClass_vtable *vptr;
};
// vtables structures
struct DeadClass_vtable
{
  char *DeadClass_gc_map;
};


// methods dec


extern void * prev;
// vtables
struct DeadClass_vtable DeadClass_vtable_ = 
{
  &DeadClass_gc_map,
};


// methods

// main method
char * Tiger_main_locals_gc_map = "";
struct Tiger_main_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
};

int Tiger_main ()
{
  struct Tiger_main_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "";
  frame.arguments_base_address = "";
  frame.locals_gc_map = Tiger_main_locals_gc_map;



  System_out_println (10);
}




