// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// structures

char * Sum_gc_map = "";

struct Sum
{
  struct Sum_vtable *vptr;
};

char * Doit_gc_map = "";

struct Doit
{
  struct Doit_vtable *vptr;
};
// vtables structures
struct Sum_vtable
{
  char *Sum_gc_map;
};

struct Doit_vtable
{
  char *Doit_gc_map;
  int (*doit)();
};


// methods dec
int Doit_doit(struct Doit * this, int n);


extern void * prev;
// vtables
struct Sum_vtable Sum_vtable_ = 
{
  &Sum_gc_map,
};

struct Doit_vtable Doit_vtable_ = 
{
  &Doit_gc_map,
  Doit_doit,
};


// methods
char * Doit_doit_arguments_gc_map = "10";
char * Doit_doit_locals_gc_map = "00";
struct Doit_doit_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
};

int Doit_doit(struct Doit * this, int n)
{
  struct Doit_doit_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Doit_doit_arguments_gc_map;
  frame.arguments_base_address = &this;
  frame.locals_gc_map = Doit_doit_locals_gc_map;


  int sum;
  int i;

  i = 0;
  sum = 0;
  while (i < n)
  {
    sum = sum + i;
    i = i + 1;
    }

  prev  = frame.prev;
  return sum;
}

// main method
char * Tiger_main_locals_gc_map = "1";
struct Tiger_main_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
  struct Doit *	x_0;
};

int Tiger_main ()
{
  struct Tiger_main_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "";
  frame.arguments_base_address = "";
  frame.locals_gc_map = Tiger_main_locals_gc_map;


  frame.x_0 = 0;

  System_out_println ((frame.x_0=((struct Doit*)(Tiger_new (&Doit_vtable_, sizeof(struct Doit)))), frame.x_0->vptr->doit(frame.x_0, 101)));
}




