// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// structures

char * test_gc_map = "";

struct test
{
  struct test_vtable *vptr;
};

char * A_gc_map = "1";

struct A
{
  struct A_vtable *vptr;
  int*  a;
};
// vtables structures
struct test_vtable
{
  char *test_gc_map;
};

struct A_vtable
{
  char *A_gc_map;
  int (*Do)();
};


// methods dec
int A_Do(struct A * this);


extern void * prev;
// vtables
struct test_vtable test_vtable_ = 
{
  &test_gc_map,
};

struct A_vtable A_vtable_ = 
{
  &A_gc_map,
  A_Do,
};


// methods
char * A_Do_arguments_gc_map = "1";
char * A_Do_locals_gc_map = "";
struct A_Do_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
};

int A_Do(struct A * this)
{
  struct A_Do_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = A_Do_arguments_gc_map;
  frame.arguments_base_address = &this;
  frame.locals_gc_map = A_Do_locals_gc_map;



  this->a = (int*)Tiger_new_array(50);
  this->a = (int*)Tiger_new_array(50);
  this->a = (int*)Tiger_new_array(24);
  prev  = frame.prev;
  return 0;
}

// main method
char * Tiger_main_locals_gc_map = "1";
struct Tiger_main_gc_frame{
  void 	*prev;
  char 	*arguments_gc_map;
  int 	*arguments_base_address;
  char 	*locals_gc_map;
  struct A *	x_0;
};

int Tiger_main ()
{
  struct Tiger_main_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "";
  frame.arguments_base_address = "";
  frame.locals_gc_map = Tiger_main_locals_gc_map;


  frame.x_0 = 0;

  System_out_println ((frame.x_0=((struct A*)(Tiger_new (&A_vtable_, sizeof(struct A)))), frame.x_0->vptr->Do(frame.x_0)));
}




